### ISSUE TITLE
Raspbian Buster Lite: libQt5OpenGL.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by caseyanderson** [redFrik/supercolliderStandaloneRPI2#1]
Hey Fredrik!

I just tried following your instructions to build this standalone under the most recent version of `raspbian`, `2019-07-10-raspbian-buster-lite.zip`, and have run across a missing file issue that prevents `SC` from starting. When I tried to run `SC` with `xvfb-run --auto-servernum ./sclang -a -l ~/supercolliderStandaloneRPI2/sclang.yaml` I got the following error:

```
./sclang: error while loading shared libraries: libQt5OpenGL.so.5: cannot open shared object file: No such file or directory
```

I am afraid I do not have time at the moment to research this more thoroughly, as I need to roll back to a version of `raspbian` that I know works with this standalone in order to finish prepping for a workshop I have to run this week, but wanted to let you know about this in the meantime.

I do see some discussion of this particular missing file/library being an issue in `Debian Buster` generally...if I have some time over the weekend I will poke around and see if I can find a simple fix.

**Comment by redFrik** [comment]
thanks for the report.  yes, i know the of the issue but have been waiting for sc3.10.3 to be released before creating a new standalone. so yes, safest to go back to raspbian stretch.

**Comment by caseyanderson** [comment]
ah, great, thanks for the super fast reply/confirmation. ill be on the lookout for sc3.10.3 release and will try again then.

thank you so much for all of your work on these standalones, btw! they are **crucial** to my teaching/music practice. if you ever need someone to test things along the way to future releases don't hesitate to drop me a line, would be happy to help out however I can!

**Comment by redFrik** [comment]
happy you like them.  here's now 3.10.3.  tested under buster and stretch and seem to work ok. no help system though.
