### ISSUE TITLE
Interpreter Inactive

### ISSUE THREAD

**Issue by moskalyk** [redFrik/supercolliderStandaloneRPI2#2]
Running on a Raspberry Pi 3

Running `scide` in the terminal, the error I get: 

`scide warning: Failed to load fallback translation file`

In the ide I get: `Interpreter has quit. [Exit code: 0]`

Attempting to rerun headless, the server is able to run, qjack shows connection, but no audio.

Any tips?

**Comment by redFrik** [comment]
thanks for report but sorry i can't reproduce here (rpi3, buster desktop).

do you experience the same problem if you start scide by doubleclicking the SuperColliderIDE.desktop icon in the standalone folder?

are you sure you're in the right folder (`cd supercolliderStandaloneRPI2`) before running `scide`?

if you run the command `ls /usr/local/bin/sc*` do you see the three files...
`/usr/local/bin/scide /usr/local/bin/sclang /usr/local/bin/scsynth/`
?

maybe you tried to build supercollider from scratch and still have that installed?  i think there was an issue recently with missing translation files in sc3.11.
(you don't need to uninstall that build, just make sure you're inside supercolliderStandaloneRPI2 before running scide.)

**Comment by moskalyk** [comment]
Thank you for the quick reply. 

I've tried reflashing on a clean Raspian OS microsd with `arm_64bit=1` and without, same thing.

Running `ls /usr/local/bin/sc*` and I don't see the files as listed. Is this the intended result?

Double clicking desktop file yields an error, but running `./run.sh` results in the same thing stated above.

Additionally, tried running on a different pi, B+ v2, and after running `scide` get `Illegal Instruction` and same result with the `./sclang -a -l ~/supercolliderStandaloneRPI2/sclang.yaml mycode.scd` command.

**Comment by redFrik** [comment]
yes, that ls /usr... command should return nothing. (it was just a wild guess that you had a conflicting sc install from the [official build instructions](https://github.com/supercollider/supercollider/blob/develop/README_RASPBERRY_PI.md) )

again sorry, i can't figure out what is wrong.  here's a from-scratch-install screencast that show how i get it running... https://vimeo.com/397466041

**Comment by moskalyk** [comment]
Thank you for the video, not a problem. It might be a hardware problem, as I realized I'm getting low voltage signals (lightning bolt + red led flashing). 

Going to try to change up power cables and possibly a new microsd, if not build from source.
