### ISSUE TITLE
Automatic start does not work on a new machine after cloning the system on a working device.

### ISSUE THREAD

**Issue by prko** [redFrik/supercolliderStandaloneRPI2#3]
Dear redFrik,

I installed supercolliderStandaloneRPI2 on my Raspberry Pi 4B. It works very well.
Today I cloned the system SD card using "SD Card Copier" on the Raspberry Pi 4B.
Then, I booted a Raspberry Pi 3B+ using a cloned SD card.
I can run python, SuperCollider and Jack.
I can execute the following one-line command in a terminal window, which comes in the last line opened by typing "crontab -e" in a terminal window.
` cd /home/pi/supercolliderStandaloneRPI2 && ./autostart.sh`

However, this line is not executed on Raspberry Pi 3B+ when booting Raspberry Pi 3B+.

Using the same method, I copied the system from a Raspberry Pi 4B to another Raspberry 4B. Again, it worked well, and the command in "crontab -e" works well.

Why does it not automatically work when booting on Raspberry 3B+?
Is there a resolution to resolve the problem?
Thank you very much for your help!

**Comment by redFrik** [comment]
thanks for the report.  strange.  i'm not sure, will have to investigate.
but a quick test you can do is to add the line...
`sleep 10`
in autostart.sh and see if that helps.

**Comment by prko** [comment]
Thank you for your advice! It resolves the problem perfectly!

**Comment by redFrik** [comment]
excellent!  happy to hear it is working.
